name: Clean Up vCluster

on:
  pull_request:
    types: [closed, unlabeled]

jobs:
  cleanup:
    if: (github.event.action == 'closed' && github.event.pull_request.merged == true) || (github.event.action == 'unlabeled' && github.event.label.name == 'test')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout Main Branch (only if PR is merged)
      - name: Checkout Main Branch
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT_TOKEN }}

      # Step 2: Merge Feature Branch into Main (only if PR is merged)
      - name: Merge Feature Branch into Main
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          FEATURE_BRANCH="feature-test-${{ github.event.pull_request.head.sha }}"
          git fetch origin $FEATURE_BRANCH
          git merge --no-ff --allow-unrelated-histories origin/$FEATURE_BRANCH -m "Merge deployment.yaml from PR #${{ github.event.pull_request.number }} into main"
          git push origin main

      # Step 3: Delete Feature Branch (only if PR is merged)
      - name: Delete Feature Branch
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          FEATURE_BRANCH="feature-test-${{ github.event.pull_request.head.sha }}"
          git push origin --delete $FEATURE_BRANCH

      # Step 4: Install vCluster CLI
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
        with:
          url: ${{ secrets.VCLUSTER_PLATFORM_URL }}
          access-key: ${{ secrets.VCLUSTER_ACCESS_KEY }}

      # Step 5: Delete vCluster
      - name: Delete vCluster
        env:
          NAME: pr-${{ github.event.pull_request.number }}
        run: |
          vcluster platform delete vcluster $NAME --project default --force || echo "vCluster $NAME not found or already deleted"
